routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\PostController;
use App\Http\Controllers\Auth\LoginController;
use App\Http\Controllers\Auth\RegisterController;
use App\Http\Controllers\Auth\LogoutController;
use App\Http\Controllers\TestController;

Route::get('/', function () {
    return view('home');
});


Route::resource("posts", PostController::class);


Route::get('/test',[TestController::class , 'TestActions'])
// routes/web.php




// Authentication routes
Route::get('login', [LoginController::class, 'showLoginForm'])->name('login');
Route::post('login', [LoginController::class, 'login']);
Route::post('logout', [LogoutController::class, 'logout'])->name('logout');
Route::get('register', [RegisterController::class, 'showRegistrationForm'])->name('register');
Route::post('register', [RegisterController::class, 'register']);

app/Models/Post.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    use HasFactory;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'title',
        'description',
        'image',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array
     */
    protected $casts = [
        'created_at' => 'datetime',
        'updated_at' => 'datetime',
    ];

    /**
     * Get the URL to the post's image.
     *
     * @return string
     */
    public function getImageUrlAttribute()
    {
        if ($this->image) {
            return asset('images/blog/' . $this->image);
        }
        return asset('images/blog/noimage.jpg');
    }
}

app/Models/User.php
<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * Get the attributes that should be cast.
     *
     * @return array<string, string>
     */
    protected function casts(): array
    {
        return [
            'email_verified_at' => 'datetime',
            'password' => 'hashed',
        ];
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

abstract class Controller
{
    //
}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use App\Models\Post;
use Illuminate\Http\Request;
use Illuminate\Support\Str;

class PostController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $posts = Post::paginate(5);
        return view("posts.index", compact("posts"));
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        return view("posts.create");
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        $request->validate([
            'title' => 'required|string|max:255',
            'description' => 'required|string',
            'image' => 'nullable|image|mimes:jpeg,png,jpg,gif|max:2048'
        ]);

        try {
            $image = $request->file('image');
            $imageName = null;

            if ($image && $image->isValid()) {
                $path = "images/blog";
                $extension = $image->getClientOriginalExtension();
                do {
                    $imageName = Str::random(10) . '.' . $extension;
                } while (file_exists($path . '/' . $imageName));
                $image->move($path, $imageName);
            }

            Post::create([
                "title" => $request->title,
                "description" => $request->description,
                "image" => $imageName // Store the image name
            ]);

            return redirect()->route("post.index")->with("success", "The new post has been successfully added!");
        } catch (\Exception $e) {
            echo ($e->getMessage());
        }
    }

    /**
     * Display the specified resource.
     */
    public function show($id)
    {
        $post = Post::findOrFail($id);
        return view("posts.show", compact("post"));
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit($id)
    {
        $post = Post::findOrFail($id);
        return view("posts.edit", compact("post"));
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'title' => 'required|string|max:255',
            'description' => 'required|string',
            'image' => 'nullable|image|mimes:jpeg,png,jpg,gif|max:2048'
        ]);

        try {
            $post = Post::findOrFail($id);
            $image = $request->file('image');
            $imageName = $post->image;

            if ($image && $image->isValid()) {
                $path = "images/blog";
                $extension = $image->getClientOriginalExtension();
                do {
                    $imageName = Str::random(10) . '.' . $extension;
                } while (file_exists($path . '/' . $imageName));
                $image->move($path, $imageName);

                // Delete the old image if a new one is uploaded
                if ($post->image && file_exists($path . '/' . $post->image)) {
                    unlink($path . '/' . $post->image);
                }
            }

            $post->update([
                "title" => $request->title,
                "description" => $request->description,
                "image" => $imageName // Update the image name
            ]);

            return redirect()->route("post.index")->with("success", "The post has been successfully updated!");
        } catch (\Exception $e) {
            echo ($e->getMessage());
        }
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy($id)
    {
        try {
            $post = Post::findOrFail($id);
            $path = "images/blog";

            // Delete the image if it exists
            if ($post->image && file_exists($path . '/' . $post->image)) {
                unlink($path . '/' . $post->image);
            }

            $post->delete();

            return redirect()->route("post.index")->with("success", "The post has been successfully deleted!");
        } catch (\Exception $e) {
            echo ($e->getMessage());
        }
    }
}

app/Http/Controllers/TestController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class TestController extends Controller
{
    public function TestActions(){
        
        return 'test action';
    }
}

resources/views/Layouts/header.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    @vite(['resources/js/app.js'])

    <!-- Styles -->
    @vite(['resources/css/app.css'])
    <style>
        body {
            background-image: url('images/flower.jpg');
            background-size: cover; /* Pour ajuster l'image à la taille de l'écran */
            background-position: center; /* Pour centrer l'image */
            background-repeat: no-repeat; /* Pour éviter la répétition de l'image */
            /* Autres styles CSS pour votre body */
        }
    </style>
</head>
<body class="bg-gray-200 h-screen antialiased leading-none font-sans">
    <div id="app">
        <header class="bg-gray-200 py-6">
            <div class="container mx-auto flex justify-between items-center px-6">
                <div>
                    <a href="{{ url('/') }}" class="text-lg font-semibold text-gray-800 no-underline">
                        {{ config('app.name', 'Laravel') }}
                    </a>
                </div>
                <nav class="space-x-4 text-gray-800 text-sm sm:text-base">
                    <a class="no-underline hover:underline" href="/">Home</a>
                    <a class="no-underline hover:underline" href="/posts">Post</a>
                    @guest
                        <a class="no-underline hover:underline" href="{{ route('login') }}">{{ __('Login') }}</a>
                        @if (Route::has('register'))
                            <a class="no-underline hover:underline" href="{{ route('register') }}">{{ __('Register') }}</a>
                        @endif
                    @else
                        <span>{{ Auth::user()->name }}</span>

                        <a href="{{ route('logout') }}"
                           class="no-underline hover:underline"
                           onclick="event.preventDefault();
                                document.getElementById('logout-form').submit();">{{ __('Logout') }}</a>
                        <form id="logout-form" action="{{ route('logout') }}" method="POST" class="hidden">
                            {{ csrf_field() }}
                        </form>
                    @endguest
                </nav>
            </div>
        </header>

        <main class="py-8">
            @yield('content')
        </main>

        <footer>
            @include('layouts.footer')
        </footer>
    </div>
</body>
</html>

resources/views/home.blade.php
@extends('Layouts.header')
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    @vite(['resources/css/app.css'])
</head>
<body>
    
</body>
</html>

resources/views/posts/create.blade.php
@extends('layouts.header')

@section('content')

@section("titre", "Ajouter un nouveau post")
@section("contenu")
    <h1 class="mt-2 mb-2">Créer un nouveau post</h1>   

    {{-- Display success message if post creation was successful --}}
    @if(session()->has('success'))
        <div class="alert alert-success">
            {{ session()->get('success') }}
        </div>
    @endif

    {{-- Display error messages if there are any --}}
    @if($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                    <li> {{$error}} </li>
                @endforeach
            </ul>
        </div>
    @endif

    <form method="POST" action="{{ route('posts.store') }}" enctype="multipart/form-data">
                @csrf
        <h1>hello soade</h1>
    </form>
@endsection

resources/views/posts/edit.blade.php
@extends('Layouts.header')

@section('content')
    <div class="min-h-screen flex justify-center items-center bg-gray-100">
        <div class="max-w-md w-full bg-white p-8 rounded-lg shadow-md">
            <h2 class="text-xl font-semibold mb-4">Edit Post</h2>

            <form method="POST"  action="{{ route('posts.update', $post->id) }}" enctype="multipart/form-data">
                @csrf
                @method('PUT')

                <div class="mb-4">
                    <label for="title" class="block text-sm font-medium text-gray-700">Title</label>
                    <input id="title" type="text" class="mt-1 p-2 block w-full border border-gray-300 rounded-md focus:outline-none focus:ring-indigo-500 focus:border-indigo-500" name="title" value="{{ $post->title }}" required autofocus>
                </div>

                <div class="mb-4">
                    <label for="description" class="block text-sm font-medium text-gray-700">Description</label>
                    <textarea id="description" class="mt-1 p-2 block w-full border border-gray-300 rounded-md focus:outline-none focus:ring-indigo-500 focus:border-indigo-500" name="description" rows="5" required>{{ $post->description }}</textarea>
                </div>

                <div class="mb-4">
                    <label for="image" class="block text-sm font-medium text-gray-700">Image</label>
                    <input id="image" type="file" class="mt-1 p-2 block w-full border border-gray-300 rounded-md focus:outline-none focus:ring-indigo-500 focus:border-indigo-500" name="image" accept="image/*">
                </div>

                <div class="flex justify-between">
                    <button type="submit" class="bg-blue-500 hover:bg-blue-600 text-white font-bold py-2 px-4 rounded focus:outline-none focus:ring-2 focus:ring-blue-400">Update Post</button>
                    <a href="{{ route('posts.index') }}" class="bg-gray-300 hover:bg-gray-400 text-gray-700 font-bold py-2 px-4 rounded focus:outline-none focus:ring-2 focus:ring-gray-400">Cancel</a>
                </div>
            </form>
        </div>
    </div>
@endsection

resources/views/posts/index.blade.php
@extends("Layouts.header")
@section("title", "Liste des articles de blog")

@section("content")
    <div class="container mx-auto px-4 py-8">
        <h2 class="text-2xl font-semibold mb-4">Liste des articles de blog</h2>

        @if(session()->has("success"))
            <div class="bg-green-100 border border-green-400 text-green-700 px-4 py-3 rounded relative mb-4" role="alert">
                {{ session("success") }}
            </div>
        @endif

        <a href="{{ route('posts.create') }}" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded mb-4 inline-block">Nouvel Post</a>

        @isset($posts)
            <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
                @foreach($posts as $post)
                    <div class="bg-white shadow-md rounded-lg overflow-hidden">
                        @if($post->image)
                            <img src="{{ asset('images/blog/' . $post->image) }}" class="w-full h-48 object-cover" alt="{{ $post->title }}" />
                        @else
                            <img src="{{ asset('images/blog/noimage.jpg') }}" class="w-full h-48 object-cover" alt="no-image" />
                        @endif
                        <div class="p-4">
                            <h5 class="text-lg font-semibold mb-2">{{ $post->title }}</h5>
                            <p class="text-gray-700 text-sm mb-4">{{ \Illuminate\Support\Str::limit($post->description, 100) }}</p>
                            <div class="flex space-x-2">
                                <a href="{{ route('posts.show', $post->id) }}" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-1 px-2 rounded text-sm"><i class="bi bi-eye"></i> Voir</a>
                                <a href="{{ route('posts.edit', $post->id) }}" class="bg-green-500 hover:bg-green-700 text-white font-bold py-1 px-2 rounded text-sm"><i class="bi bi-pencil"></i> Modifier</a>
                                <form action="{{ route('posts.destroy', $post->id) }}" method="post" class="inline">
                                    @csrf
                                    @method("DELETE")
                                    <button type="submit" class="bg-red-500 hover:bg-red-700 text-white font-bold py-1 px-2 rounded text-sm" onclick="return confirm('Voulez-vous supprimer l\'article : {{ $post->title }}?')">
                                        <i class="bi bi-trash"></i> Supprimer
                                    </button>
                                </form>
                            </div>
                        </div>
                    </div>
                @endforeach
            </div>

            <div class="mt-6">
                {{ $posts->links('pagination::tailwind') }}
            </div>
        @endisset
    </div>
@endsection

resources/views/posts/show.blade.php
@extends('Layouts.header')

@section('content')
    <div class="min-h-screen flex justify-center items-center bg-gray-100">
        <div class="max-w-md w-full bg-white p-8 rounded-lg shadow-md">
            <h2 class="text-xl font-semibold mb-4">{{ $post->title }}</h2>

            <div class="card-body">
                <p class="mb-4">{{ $post->description }}</p>
                @if ($post->image)
                    <img src="{{ asset('storage/' . $post->image) }}" alt="{{ $post->title }}" class="w-full rounded-lg">
                @endif
            </div>
        </div>
    </div>
@endsection